[tool.poetry]
name = "mock-graph-data-generator-streamlit"
version = "0.7.0"
description = ""
authors = ["Jason Koo <jalakoo@gmail.com>"]
readme = "README.md"
packages = [{include = "graph_data_generator_streamlit"}]

[tool.poetry.dependencies]
python = "^3.11"
streamlit = ">=1.27,<2.0"
neo4j-uploader = ">=0.2.0,<0.3.0"
pyclip = ">=0.7,<1.0"
graph-data-generator = ">=0.3.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
