[tool.poetry]
name = "mock_generators"
version = "0.1.0"
description = ""
authors = ["Jason Koo <jalakoo@gmail.com>"]
readme = "README.md"
packages = [{include = "mock_generators"}]

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.15.1"
lorem-text = "^2.1"
faker = "^15.3.3"
streamlit-extras = "^0.2.4"
streamlit-toggle-switch = "^1.0.2"
hydralit-components = "^1.0.10"
pytest = "^7.2.0"
dataclasses-json = "^0.5.7"
pyperclip = "^1.8.2"
streamlit-agraph = "^0.0.45"
python-dotenv = "^1.0.0"
openai = "^0.26.5"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"

[tool.pytest.ini_options]
pythonpath = [
  ".", "mock_generators"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
